import { Product } from "@/types";

export const categories = ["Home Decor", "Accessories", "Lifestyle"];

export const mockProducts: Product[] = [
  {
    id: "1",
    slug: "ceramic-vase",
    name: "Ceramic Vase",
    price: 1280,
    comparePrice: 1600,
    images: [
      "https://picsum.photos/seed/vase1/600/600",
      "https://picsum.photos/seed/vase2/600/600",
      "https://picsum.photos/seed/vase3/600/600",
    ],
    description: "手工陶瓷花瓶，簡約設計，適合各種居家風格。",
    details: "這款手工陶瓷花瓶由經驗豐富的工匠精心製作，採用高溫燒製的優質陶土，表面施以啞光釉料，呈現溫潤細膩的質感。簡約的線條設計，無論擺放在客廳、書房或臥室，都能為空間增添一份寧靜的美感。",
    specs: { "材質": "高溫陶瓷", "尺寸": "直徑 12cm x 高 25cm", "重量": "800g", "產地": "台灣" },
    category: "Home Decor",
    stock: 15,
    rating: 4.8,
  },
  {
    id: "2",
    slug: "linen-tote-bag",
    name: "Linen Tote Bag",
    price: 890,
    images: [
      "https://picsum.photos/seed/bag1/600/600",
      "https://picsum.photos/seed/bag2/600/600",
    ],
    description: "天然亞麻手提袋，輕巧耐用，日常通勤的最佳選擇。",
    details: "選用法國進口天然亞麻布料，經過預縮處理，不易變形。寬敞的內部空間配有一個拉鏈內袋，方便收納隨身物品。加固的手提帶設計，承重力強，是日常通勤、購物的理想選擇。",
    specs: { "材質": "100% 天然亞麻", "尺寸": "寬 38cm x 高 42cm x 底寬 12cm", "重量": "280g", "產地": "台灣" },
    category: "Accessories",
    stock: 30,
    rating: 4.6,
  },
  {
    id: "3",
    slug: "scented-candle",
    name: "Scented Candle",
    price: 680,
    comparePrice: 850,
    images: [
      "https://picsum.photos/seed/candle1/600/600",
      "https://picsum.photos/seed/candle2/600/600",
      "https://picsum.photos/seed/candle3/600/600",
    ],
    description: "天然大豆蠟香氛蠟燭，溫暖木質調，營造居家氛圍。",
    details: "使用 100% 天然大豆蠟，搭配精選木質調精油，燃燒時散發溫暖沉穩的香氣。附贈木質燭蓋，不使用時可蓋上保持香味。燃燒時間約 45 小時。",
    specs: { "材質": "天然大豆蠟 + 精油", "尺寸": "直徑 8cm x 高 10cm", "重量": "250g", "燃燒時間": "約 45 小時" },
    category: "Home Decor",
    stock: 50,
    rating: 4.9,
  },
  {
    id: "4",
    slug: "wooden-coaster-set",
    name: "Wooden Coaster Set",
    price: 520,
    images: [
      "https://picsum.photos/seed/coaster1/600/600",
      "https://picsum.photos/seed/coaster2/600/600",
    ],
    description: "原木杯墊四入組，手工打磨，溫潤質感。",
    details: "精選胡桃木手工切割打磨，保留天然木紋之美。表面塗覆食品級木蠟油，防水防污。每一片都是獨一無二的自然紋路，為您的桌面增添溫暖氣息。",
    specs: { "材質": "天然胡桃木", "尺寸": "直徑 10cm x 厚 0.8cm", "數量": "4 入", "產地": "台灣" },
    category: "Home Decor",
    stock: 25,
    rating: 4.5,
  },
  {
    id: "5",
    slug: "minimalist-wall-clock",
    name: "Minimalist Wall Clock",
    price: 1680,
    comparePrice: 2100,
    images: [
      "https://picsum.photos/seed/clock1/600/600",
      "https://picsum.photos/seed/clock2/600/600",
    ],
    description: "極簡掛鐘，無數字設計，靜音機芯。",
    details: "極簡主義設計掛鐘，捨去多餘裝飾，僅以指針標示時間。採用靜音掃秒機芯，運轉無聲，不打擾您的寧靜時光。金屬框體搭配木質指針，質感與實用兼具。",
    specs: { "材質": "金屬框 + 木質指針", "尺寸": "直徑 30cm", "電池": "AA 電池 x 1（不附）", "機芯": "靜音掃秒" },
    category: "Home Decor",
    stock: 10,
    rating: 4.7,
  },
  {
    id: "6",
    slug: "leather-card-holder",
    name: "Leather Card Holder",
    price: 750,
    images: [
      "https://picsum.photos/seed/card1/600/600",
      "https://picsum.photos/seed/card2/600/600",
      "https://picsum.photos/seed/card3/600/600",
    ],
    description: "植鞣皮革卡夾，手工縫線，越用越有味道。",
    details: "採用義大利進口植鞣皮革，隨使用時間推移，皮革會逐漸產生獨特的色澤變化。手工蠟線縫製，堅固耐用。可放置 6-8 張卡片，輕薄便攜。",
    specs: { "材質": "義大利植鞣牛皮", "尺寸": "長 10cm x 寬 7cm", "容量": "6-8 張卡片", "產地": "台灣手工" },
    category: "Accessories",
    stock: 20,
    rating: 4.8,
  },
  {
    id: "7",
    slug: "brass-pen-holder",
    name: "Brass Pen Holder",
    price: 980,
    images: [
      "https://picsum.photos/seed/pen1/600/600",
      "https://picsum.photos/seed/pen2/600/600",
    ],
    description: "黃銅筆筒，實心材質，桌面的品味之選。",
    details: "實心黃銅鑄造，重量感十足，穩固不易傾倒。表面經過拋光處理，隨時間推移會自然產生銅綠氧化效果，展現獨特的歲月痕跡。簡潔圓柱造型，為您的辦公桌增添一份質感。",
    specs: { "材質": "實心黃銅", "尺寸": "直徑 6cm x 高 10cm", "重量": "450g", "表面處理": "拋光" },
    category: "Lifestyle",
    stock: 12,
    rating: 4.4,
  },
  {
    id: "8",
    slug: "cotton-throw-blanket",
    name: "Cotton Throw Blanket",
    price: 1480,
    images: [
      "https://picsum.photos/seed/blanket1/600/600",
      "https://picsum.photos/seed/blanket2/600/600",
      "https://picsum.photos/seed/blanket3/600/600",
    ],
    description: "純棉針織毯，柔軟親膚，沙發上的慵懶伴侶。",
    details: "選用新疆長絨棉，經精梳處理後針織而成，柔軟蓬鬆、透氣親膚。簡約的編織紋路搭配流蘇邊飾，披在沙發上即是一道美麗的風景。可機洗，方便照顧。",
    specs: { "材質": "100% 新疆長絨棉", "尺寸": "130cm x 170cm", "重量": "900g", "洗滌": "可機洗（冷水柔洗）" },
    category: "Lifestyle",
    stock: 18,
    rating: 4.7,
  },
  {
    id: "9",
    slug: "glass-water-bottle",
    name: "Glass Water Bottle",
    price: 620,
    images: [
      "https://picsum.photos/seed/bottle1/600/600",
      "https://picsum.photos/seed/bottle2/600/600",
    ],
    description: "耐熱玻璃水瓶，竹蓋設計，環保又時尚。",
    details: "高硼矽耐熱玻璃製成，可承受 -20°C 至 150°C 溫差。天然竹蓋搭配矽膠密封圈，防漏設計。瓶身附贈隔熱布套，防燙又防摔。容量 500ml，適合日常隨身攜帶。",
    specs: { "材質": "高硼矽玻璃 + 天然竹蓋", "容量": "500ml", "耐溫": "-20°C ~ 150°C", "配件": "隔熱布套" },
    category: "Lifestyle",
    stock: 40,
    rating: 4.3,
  },
  {
    id: "10",
    slug: "woven-storage-basket",
    name: "Woven Storage Basket",
    price: 860,
    comparePrice: 1080,
    images: [
      "https://picsum.photos/seed/basket1/600/600",
      "https://picsum.photos/seed/basket2/600/600",
    ],
    description: "手工編織收納籃，天然海草材質，美觀又實用。",
    details: "選用天然海草手工編織，每一個籃子都帶有獨特的自然紋理。適合收納雜誌、毛巾、玩具等物品，也可作為花盆套使用。底部平整穩固，不易傾倒。",
    specs: { "材質": "天然海草", "尺寸": "直徑 28cm x 高 25cm", "重量": "350g", "產地": "越南手工" },
    category: "Home Decor",
    stock: 22,
    rating: 4.6,
  },
];
